// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Config = require("./config.bs.js");
var Puppeteer = require("puppeteer");
var Viewport$BsPuppeteer = require("bs-puppeteer/src/Viewport.js");
var Puppeteer$BsPuppeteer = require("bs-puppeteer/src/Puppeteer.js");

function typeOptionsToJs(param) {
  return {
          delay: param.delay
        };
}

function typeOptionsFromJs(param) {
  return {
          delay: param.delay
        };
}

function makeTypeOptions(d) {
  return typeOptionsToJs({
              delay: d
            });
}

function clickButtonWithText(page, text) {
  return page.waitForXPath("//button[contains(., '" + (text + "')]"), undefined).then((function (button) {
                return button.click(undefined);
              }));
}

function login(page) {
  var options = {
    timeout: 5000.0,
    waitUntil: "domcontentloaded"
  };
  return page.goto("https://instagram.com", options).then((function (param) {
                        return page.waitForSelector("input[name=username]", undefined);
                      })).then((function (param) {
                      return page.type("input[name=username]", Config.username, typeOptionsToJs({
                                      delay: 100
                                    }));
                    })).then((function (param) {
                    return page.type("input[name=password]", Config.password, typeOptionsToJs({
                                    delay: 100
                                  }));
                  })).then((function (param) {
                  return page.click("[type=submit]", undefined);
                })).then((function (param) {
                return clickButtonWithText(page, "Not Now");
              }));
}

function openWindow(param) {
  var opt = Puppeteer$BsPuppeteer.makeLaunchOptions(undefined, false, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0);
  return Puppeteer.launch(opt).then((function (browser) {
                  return browser.newPage();
                })).then((function (page) {
                var vp = Viewport$BsPuppeteer.make(375, 667, undefined, undefined, undefined, undefined, /* () */0);
                page.setViewport(vp);
                return login(page);
              }));
}

openWindow(/* () */0);

exports.typeOptionsToJs = typeOptionsToJs;
exports.typeOptionsFromJs = typeOptionsFromJs;
exports.makeTypeOptions = makeTypeOptions;
exports.clickButtonWithText = clickButtonWithText;
exports.login = login;
exports.openWindow = openWindow;
/*  Not a pure module */
